name: autocomplete-sonar-analysis

trigger:
  branches:
    include:
      - master

pool:
  name: test-automation-linux
  vmImage: 'ubuntu-latest'

stages:
  - stage: TriggerSonarQubePipeline
    displayName: Job SonarQube Pipeline
    jobs:
      - job: TriggerSonarQubePipeline
        displayName: Job SonarQube Pipeline
        continueOnError: false
        steps:
          - task: SonarQubePrepare@5
            displayName: 'Prepare Sonar Qube Configuration'
            inputs:
              SonarQube: 'SonarQube-AutoComplete-Tests'
              scannerMode: 'Other'

          - task: Maven@3
            displayName: 'Run Test Suit'
            inputs:
              mavenPOMFile: 'pom.xml'
              goals: 'clean package dependency:copy-dependencies'
              options: '
                - Dsonar.sources=src/test/java
                - Dsonar.test.inclusions=src/test/java*
                - Dsonar.coverage.exclusions=src/test/java/**
                - Dmaven.tests.skip
                - Dsonar.login=342342342342352452636
                - Dsonar.java.binaries=target/classes
                - Dsonar.java.libraries=target/dependency/*.jar'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '17'
              sonarQubeRunAnalysis: true

          - task: SonarQubePublish@4
            displayName: 'Publish Quality Gate Result'
            inputs:
              failTaskOnFailedTests: true

          - task: sonar-buildbreaker@8
            displayName: 'Break Build On Quality Gate'
            inputs:
              SonarQube: 'SonarQube-autoComplete-tests'
