name: auto-complete

trigger:
  - master

pool:
  name: test-automation-linux
  vmImage: 'ubuntu-latest'

stages:
  - stage: TriggerTestPipeline
    displayName: Stage Test Pipeline
    jobs:
      - job: TriggerTestPipeline
        displayName: Job Test Pipeline
        continueOnError: false
        steps:
          - task: DockerCompose@0
            displayName: 'Build Docker Image'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'build'

          - task: DockerCompose@0
            displayName: 'Run Test Suit'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'up'
              arguments: 'regression-test-suite'

          - task: CopyFiles@2
            displayName: 'Copy Test Report'
            inputs:
              SourceFolder: 'report'
              Contents: '**'
              TargetFolder: 'testReport'

          - task: DockerCompose@0
            displayName: 'Stop Container and Remove Volume & Image'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'down'

          - task: publish-cucumber-report-task@1
            displayName: 'Publish Cucumber Report'
            inputs:
              jsonPath: 'testReport/cucumber-reports/cucumber/Cucumber.json'


          - task: PublishTestResults@2
            displayName: 'Publish Surefire Report'
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: 'testReport/surefire-reports/TEST-*.xml'
              failTaskOnFailedTests: true
              testRunTitle: 'Surefire Test Reports'