version: '3.7'
services:

  autocomplete:
    build: .
    stdin_open: true
    tty: true
    container_name: autocomplete
    image: autocomplete:${VERSION}

  gui-test-suite:
    stdin_open: true
    tty: true
    container_name: gui-test-suite
    image: autocomplete:${VERSION}
    command:
      mvn test -Dspring.profiles.active="dev" -Dcucumber.filter.tags="@GUI"
    volumes:
      - type: bind
        source: ./report/${BUILD_NUMBER}/gui
        target: /auto-complete/target/cucumber-reports/

  api-test-suite:
    stdin_open: true
    tty: true
    container_name: api-test-suite
    image: autocomplete:${VERSION}
    command:
      mvn test -Dcucumber.filter.tags="@API"
    volumes:
      - type: bind
        source: ./report/${BUILD_NUMBER}/api
        target: /auto-complete/target/cucumber-reports/

networks:
  default:
    external:
      name: test