image: mavengoldeneye/maven-chrome-openjdk-14

build:
  stage: build
  script:
    - mvn compile
    - mvn clean install

test:
  stage: test
  script:
    - mvn test -Dspring.profiles.active="dev" -Dcucumber.filter.tags="@GUI"